### PR TITLE
Changed Font Awesome email icon to envelope-square

### PR DESCRIPTION
**Pull request by jdefelice**
The envelopment-square fits better with the other icons.

### CODE REVIEW

**Comment by fourtonfish** [comment]
@jdefelice Thanks! I'll be updating this on http://simplesharingbuttons.com/ as well.

**Comment by bolaram** [comment]
@fourtonfish can we add Instagram and Youtube logo also for sharing ??

**Comment by fourtonfish** [comment]
@bolaram I think you might be misunderstanding this project. These are buttons you can add to your site so that other people can share it on social media sites, for example "Tweet this page" or "Share this page on Facebook".

I'm guessing you are talking about links to your actual Instagram/YouTube?

**Comment by bolaram** [comment]
yeah ,, i wanted extra buttons like  "Share this page on Youtube" & "Share this on Instagram" ...etc..

**Comment by bolaram** [comment]
@fourtonfish

**Comment by fourtonfish** [comment]
I'm not sure that's actually possible, you can only upload videos to
YouTube and images to Instagram, unlike Twitter or Facebook, where you can
share any kind of web content.

If I'm understanding what you're asking about -- an option to reupload a
video you're watching to YouTube, or similarly an image to Instagram, I'm
afraid that's way beyond the original idea of this project.

**Comment by fourtonfish** [comment]
@bolaram I'm not sure that's actually possible, you can only upload videos to YouTube and images to Instagram, unlike Twitter or Facebook, where you can share any kind of web content.

If I'm understanding what you're asking about -- an option to reupload a video you're watching to YouTube, or similarly an image to Instagram, I'm afraid that's way beyond the original idea of this project.

**Pull request merged**
